<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\rpgmodder.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

        <Version>2.0.0</Version>
        <FileVersion>2.0.0</FileVersion>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <Authors>Vicente</Authors>
        <Company>RPGModder</Company>
        <Product>RPGModder</Product>

        <AssemblyName>RPGModder</AssemblyName>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
        <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
        <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
        <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11"/>
        <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.3.0"/>

        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RPGModder.Core\RPGModder.Core.csproj" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Dialogs\ModLinkWindow.axaml.cs">
        <DependentUpon>ModLinkWindow.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
